name: tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install npm dependencies
        run: npm ci --ignore-scripts --no-audit --no-fund

      - name: Set Git identity
        run: |
          git config --global user.name "tests"
          git config --global user.email "tests@bwatkins.dev"

      - name: Run tests
        run: npm test
